pipeline {
    agent {
        docker {
            image 'adoptopenjdk:8-jdk'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'maven -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'maven test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
