pipline {
  agent {
    docker {
      image 'maven:3-alpine'
      args '-v /root/ .m2:/root/ .m2'
    }
  }
  stages {
    stage('Build') {
      stage ('SCM Checkout '){
        git 'https://github.com/ayam999/Team28'
      }
      stage('Compile-Package'){
        sh 'mvn package'
      }
    }
  }
}
